# Page and Settings admin forms
# Example
pages:
  home:
    title: Home
    parts:
      slideshow:
        repeatable: true
        fields:
          image:
            type: image
            position: 0
          title:
            type: string
            default: Lorem Ipsum 1
            position: 1
          description:
            type: string
            default: Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            position: 2
            required: false
          button:
            type: string
            default: Call to Action
            position: 3
            required: false
      mission_statement:
        fields:
          title:
            type: string
            default: Mission Statement
            position: 0
          text:
            type: rich_text
      recent_tweets:
        fields:
          title:
            type: string
            default: Recent Tweets
            position: 0
          handle:
            type: string
            position: 1
  about:
    title: About
    parts:
      about: 
        fields:
          title: 
            type: string
            default: What is Alma?
          statement:
            type: string
            default: This body was founded by African Heads of State and Government of utilize their individual and collective power across country and regional borders.
          content:
            type: rich_text
            position: 0
      teams:
        fields:
          statement:
            type: string
            position: 1
      jobs:
        repeatable: true
        fields:
          statement:
            type: string
          content:
            type: rich_text
            position: 2
  news:
    title: News
    parts:
      news:
        fields:
          image:
            type: image
            position: 0
          statement:
            type: string
            position: 0
          resource:
            type: resource_link
            value: articles
            label: Click here to See your Articles
  events:
    title: Events
    parts:
      events:
        fields:
          resource:
            type: resource_link
            value: events
            label: Click here to See your Events
  contact:
    title: Contact
    parts:
      contact:
        fields:
          statement:
            type: string
            default: Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          contact_info:
            type: rich_text
          send_to:
            type: string

settings:
  facebook:
    type: string
    required: false
  twitter: 
    type: string
    required: false
  youtube:
    type: string
    required: false